version: "3.8"

services:
  rebate_tracing_tool:
    container_name: rebate_tracing_tool
    build: .
    ports:
      - 8188:8188
    command: "uvicorn --host '0.0.0.0' --port 8188 main:app"
    volumes:
      - ./.scrat:/.scrat
    restart: unless-stopped

volumes:
  .scrat:
